services:
  app:
    build: .
    env_file: 
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      GROQ_API_KEY: ${GROQ_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}
      PYTHONPATH: /app/backend
      LOGFIRE_IGNORE_NO_CONFIG: 1
    volumes:
      - ./backend:/app/backend
    tty: true
    stdin_open: true
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 